package nepjr.tech.metatileentities.multi.electric;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.LinkedList;
import java.util.List;
import java.util.function.Supplier;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import gregtech.api.GTValues;
import gregtech.api.capability.GregtechDataCodes;
import gregtech.api.capability.IEnergyContainer;
import gregtech.api.capability.impl.MultiblockRecipeLogic;
import gregtech.api.metatileentity.MetaTileEntity;
import gregtech.api.metatileentity.interfaces.IGregTechTileEntity;
import gregtech.api.metatileentity.multiblock.IMultiblockPart;
import gregtech.api.metatileentity.multiblock.MultiblockAbility;
import gregtech.api.metatileentity.multiblock.MultiblockDisplayText;
import gregtech.api.metatileentity.multiblock.RecipeMapMultiblockController;
import gregtech.api.pattern.BlockPattern;
import gregtech.api.pattern.FactoryBlockPattern;
import gregtech.api.pattern.MultiblockShapeInfo;
import gregtech.api.pattern.PatternMatchContext;
import gregtech.api.pattern.PatternStringError;
import gregtech.api.pattern.TraceabilityPredicate;
import gregtech.api.recipes.RecipeMaps;
import gregtech.api.recipes.recipeproperties.IRecipePropertyStorage;
import gregtech.api.util.BlockInfo;
import gregtech.api.util.GTUtility;
import gregtech.api.util.TextComponentUtil;
import gregtech.client.renderer.ICubeRenderer;
import gregtech.common.ConfigHolder;
import gregtech.common.blocks.MetaBlocks;
import gregtech.common.metatileentities.MetaTileEntities;
import nepjr.tech.api.NepTechAPI;
import nepjr.tech.api.block.IMixingModuleStats;
import nepjr.tech.api.unification.material.NTMaterials;
import nepjr.tech.client.NTTextures;
import nepjr.tech.common.blocks.BlockMixingModules.ModuleTier;
import nepjr.tech.common.blocks.BlockNTCasings.NTCasingType;
import nepjr.tech.common.blocks.NTMetaBlocks;
import nepjr.tech.metatileentities.NTMetaTileEntities;
import net.minecraft.block.state.IBlockState;
import net.minecraft.client.resources.I18n;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.network.PacketBuffer;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.text.ITextComponent;
import net.minecraft.util.text.TextFormatting;
import net.minecraft.world.World;

public class MetaTileEntityMixingVessel extends RecipeMapMultiblockController
{
	protected float processingSpeed;
	protected int moduleTier;
	private static final int minVesselSize = 2;
	private int lDist = 0;
    private int rDist = 0;
    private int bDist = 0;
    private int fDist = 0;
    private int hDist = 0;
	
	public MetaTileEntityMixingVessel(ResourceLocation metaTileEntityId) 
	{
		super(metaTileEntityId, RecipeMaps.MIXER_RECIPES);
		this.recipeMapWorkable = new MixingVesselLogic(this);
	}
	
	// Allow all fertilizers, and require them to have the same type.
    public static Supplier<TraceabilityPredicate> MIXING_MODULES = () -> new TraceabilityPredicate(blockWorldState -> {
        IBlockState blockState = blockWorldState.getBlockState();
        if (NepTechAPI.MIXING_MODULES.containsKey(blockState)) {
        	IMixingModuleStats stats = NepTechAPI.MIXING_MODULES.get(blockState);
            Object currentCoil = blockWorldState.getMatchContext().getOrPut("MixingModule", stats);
            if (!currentCoil.equals(stats)) {
                blockWorldState.setError(new PatternStringError("neptech.multiblock.pattern.error.mixing_module"));
                return false;
            }
            blockWorldState.getMatchContext().getOrPut("VABlock", new LinkedList<>()).add(blockWorldState.getPos());
            return true;
        }
        return false;
    }, () -> NepTechAPI.MIXING_MODULES.entrySet().stream()
            // sort to make autogenerated jei previews not pick random coils each game load
            .sorted(Comparator.comparingInt(entry -> entry.getValue().getTier()))
            .map(entry -> new BlockInfo(entry.getKey(), null))
            .toArray(BlockInfo[]::new))
                    .addTooltips("neptech.multiblock.pattern.error.mixing_module");
    
    public static TraceabilityPredicate mixingModules() {
        return MIXING_MODULES.get();
    }
    
    @Override
    public boolean allowsExtendedFacing() {
        return false;
    }

    @Override
    public boolean allowsFlip() {
        return false;
    }
    
    @Override
    public void addInformation(ItemStack stack, @Nullable World player, @NotNull List<String> tooltip,
                               boolean advanced) {
        super.addInformation(stack, player, tooltip, advanced);
        tooltip.add(TextFormatting.GRAY + I18n.format("neptech.mixing_vessel.tooltip1"));
        tooltip.add(TextFormatting.GRAY + I18n.format("neptech.mixing_vessel.tooltip2"));
        tooltip.add(TextFormatting.GRAY + I18n.format("neptech.mixing_vessel.tooltip3"));
        tooltip.add(TextFormatting.GRAY + I18n.format("neptech.mixing_vessel.tooltip4"));
        tooltip.add(TextFormatting.GRAY + I18n.format("neptech.mixing_vessel.tooltip5"));
        tooltip.add(TextFormatting.GRAY + I18n.format("neptech.mixing_vessel.tooltip6"));
        tooltip.add(TextFormatting.GRAY + I18n.format("neptech.mixing_vessel.tooltip7"));
        tooltip.add(TextFormatting.GRAY + I18n.format("neptech.mixing_vessel.tooltip8"));
        tooltip.add(TextFormatting.GRAY + I18n.format("neptech.mixing_vessel.tooltip9"));
    }
    
	@Override
    protected void formStructure(PatternMatchContext context) {
        super.formStructure(context);
        
        Object mixerModule = context.get("MixingModule");
        if (mixerModule instanceof IMixingModuleStats) {
            this.processingSpeed = ((IMixingModuleStats) mixerModule).getProcessingSpeed();
            this.moduleTier = ((IMixingModuleStats) mixerModule).getTier();
        } else {
            this.processingSpeed = 0;
            this.moduleTier = GTValues.ULV;
        }
	}
	
	@Override
    public void checkStructurePattern() {
        if (!this.isStructureFormed()) {
            reinitializeStructurePattern();
        }
        super.checkStructurePattern();
        if(!getAbilities(MultiblockAbility.INPUT_LASER).isEmpty())
        {
        	if(moduleTier < GTValues.UV)
        	{
        		invalidateStructure();
        	}
        }
        if(getAbilities(MultiblockAbility.INPUT_ENERGY).isEmpty() && getAbilities(MultiblockAbility.INPUT_LASER).isEmpty())
        {
        	invalidateStructure();
        }
    }
	
	@Override
    protected void addDisplayText(List<ITextComponent> textList) {
        MultiblockDisplayText.builder(textList, isStructureFormed())
                .setWorkingStatus(recipeMapWorkable.isWorkingEnabled(), recipeMapWorkable.isActive())
                .addEnergyUsageLine(recipeMapWorkable.getEnergyContainer())
                .addEnergyTierLine(GTUtility.getTierByVoltage(recipeMapWorkable.getMaxVoltage()))
                .addParallelsLine(recipeMapWorkable.getParallelLimit())
                .addCustom(tl ->
                {
                	tl.add(TextComponentUtil.translationWithColor(TextFormatting.GRAY, "neptech.processing_speed", getProcessingSpeed() * 100));
                })
                .addWorkingStatusLine()
                .addProgressLine(recipeMapWorkable.getProgressPercent());
    }
	
	/**
     * @param world     the world to check
     * @param pos       the pos to check and move
     * @param direction the direction to move
     * @return if a block is a valid wall block at pos moved in direction
     */
    public boolean isBlockEdge(@NotNull World world, @NotNull BlockPos.MutableBlockPos pos,
                               @NotNull EnumFacing direction) {
        return world.getBlockState(pos.move(direction)) ==
                NTMetaBlocks.NT_CASINGS.getState(NTCasingType.MIXER_CASING);
    }

    /**
     * @param world     the world to check
     * @param pos       the pos to check and move
     * @param direction the direction to move
     * @return if a block is a valid floor block at pos moved in direction
     */
    public boolean isBlockFloor(@NotNull World world, @NotNull BlockPos.MutableBlockPos pos,
                                @NotNull EnumFacing direction) {
        return isBlockEdge(world, pos, direction);
    }
	
	/**
     * Scans for blocks around the controller to update the dimensions
     */
    public boolean updateStructureDimensions() {
        World world = getWorld();
        EnumFacing front = getFrontFacing();
        EnumFacing back = front.getOpposite();
        EnumFacing left = front.rotateYCCW();
        EnumFacing right = left.getOpposite();

        BlockPos.MutableBlockPos lPos = new BlockPos.MutableBlockPos(getPos());
        BlockPos.MutableBlockPos rPos = new BlockPos.MutableBlockPos(getPos());
        BlockPos.MutableBlockPos fPos = new BlockPos.MutableBlockPos(getPos());
        BlockPos.MutableBlockPos bPos = new BlockPos.MutableBlockPos(getPos());
        BlockPos.MutableBlockPos hPos = new BlockPos.MutableBlockPos(getPos());

        // find the distances from the controller to the plascrete blocks on one horizontal axis and the Y axis
        // repeatable aisles take care of the second horizontal axis
        int lDist = 0;
        int rDist = 0;
        int bDist = 0;
        int fDist = 0;
        int hDist = 0;

        // find the left, right, back, and front distances for the structure pattern
        // maximum size is 25*25*25 including walls, so check 12 block radius around the controller for blocks
        for (int i = 1; i < 13; i++) {
            if (lDist == 0 && isBlockEdge(world, lPos, left)) lDist = i;
            if (rDist == 0 && isBlockEdge(world, rPos, right)) rDist = i;
            if (bDist == 0 && isBlockEdge(world, bPos, back)) bDist = i;
            if (fDist == 0 && isBlockEdge(world, fPos, front)) fDist = i;
            if (lDist != 0 && rDist != 0 && bDist != 0 && fDist != 0) break;
        }

        // height is diameter instead of radius, so it needs to be done separately
        for (int i = 1; i < 25; i++) {
            if (isBlockFloor(world, hPos, EnumFacing.DOWN)) hDist = i;
            if (hDist != 0) break;
        }

        if (lDist < minVesselSize || rDist < minVesselSize || bDist < minVesselSize || fDist < minVesselSize || hDist < minVesselSize * 2) {
            invalidateStructure();
            return false;
        }
        
        if(!areAllEqual(lDist, rDist, bDist, fDist))
        {
        	return false;
        }
        
        if(hDist != lDist * 2)
        {
        	return false;
        }
        
        if((lDist * 2) + 1 % 2 == 0)
        {
        	return false;
        }

        this.lDist = lDist;
        this.rDist = rDist;
        this.bDist = bDist;
        this.fDist = fDist;
        this.hDist = hDist;

        writeCustomData(GregtechDataCodes.UPDATE_STRUCTURE_SIZE, buf -> {
            buf.writeInt(this.lDist);
            buf.writeInt(this.rDist);
            buf.writeInt(this.bDist);
            buf.writeInt(this.fDist);
            buf.writeInt(this.hDist);
        });
        return true;
    }

	@NotNull
    @Override
    protected BlockPattern createStructurePattern() {
        // return the default structure, even if there is no valid size found
        // this means auto-build will still work, and prevents terminal crashes.
        if (getWorld() != null) updateStructureDimensions();

        // these can sometimes get set to 0 when loading the game, breaking JEI
        if (lDist < minVesselSize) lDist = minVesselSize;
        if (rDist < minVesselSize) rDist = minVesselSize;
        if (bDist < minVesselSize) bDist = minVesselSize;
        if (fDist < minVesselSize) fDist = minVesselSize;
        if (hDist < minVesselSize) hDist = minVesselSize * 2;

        if (this.frontFacing == EnumFacing.EAST || this.frontFacing == EnumFacing.WEST) {
            int tmp = lDist;
            lDist = rDist;
            rDist = tmp;
        }

        // build each row of the structure
        StringBuilder borderBuilder = new StringBuilder();     // BBBBB
        StringBuilder wallBuilder = new StringBuilder();       // BXXXB
        StringBuilder insideBuilder = new StringBuilder();     // X X
        StringBuilder roofBuilder = new StringBuilder();       // BFFFB
        StringBuilder controllerBuilder = new StringBuilder(); // BFSFB
        StringBuilder centerBuilder = new StringBuilder();     // BXKXB

        // everything to the left of the controller
        for (int i = 0; i < lDist; i++) {
            borderBuilder.append("B");
            if (i == 0) {
                wallBuilder.append("B");
                insideBuilder.append("X");
                roofBuilder.append("B");
                controllerBuilder.append("B");
                centerBuilder.append("B");
            } else {
                insideBuilder.append(" ");
                wallBuilder.append("X");
                roofBuilder.append("F");
                controllerBuilder.append("F");
                centerBuilder.append("X");
            }
        }

        // everything in-line with the controller
        borderBuilder.append("B");
        wallBuilder.append("X");
        insideBuilder.append(" ");
        roofBuilder.append("F");
        controllerBuilder.append("S");
        centerBuilder.append("K");

        // everything to the right of the controller
        for (int i = 0; i < rDist; i++) {
            borderBuilder.append("B");
            if (i == rDist - 1) {
                wallBuilder.append("B");
                insideBuilder.append("X");
                roofBuilder.append("B");
                controllerBuilder.append("B");
                centerBuilder.append("B");
            } else {
                insideBuilder.append(" ");
                wallBuilder.append("X");
                roofBuilder.append("F");
                controllerBuilder.append("F");
                centerBuilder.append("X");
            }
        }

        // build each slice of the structure
        String[] wall = new String[hDist + 1]; // "BBBBB", "BXXXB", "BXXXB", "BXXXB", "BBBBB"
        Arrays.fill(wall, wallBuilder.toString());
        wall[0] = borderBuilder.toString();
        wall[wall.length - 1] = borderBuilder.toString();

        String[] slice = new String[hDist + 1]; // "BXXXB", "X X", "X X", "X X", "BFFFB"
        Arrays.fill(slice, insideBuilder.toString());
        slice[0] = wallBuilder.toString();
        slice[slice.length - 1] = roofBuilder.toString();

        String[] center = Arrays.copyOf(slice, slice.length); // "BXKXB", "X X", "X X", "X X", "BFSFB"
        if (this.frontFacing == EnumFacing.NORTH || this.frontFacing == EnumFacing.SOUTH) {
            center[0] = centerBuilder.reverse().toString();
            center[center.length - 1] = controllerBuilder.reverse().toString();
        } else {
            center[0] = centerBuilder.toString();
            center[center.length - 1] = controllerBuilder.toString();
        }

        TraceabilityPredicate wallPredicate = states(getCasingState());
        TraceabilityPredicate basePredicate = autoAbilities().or(abilities(MultiblockAbility.INPUT_ENERGY).setMaxGlobalLimited(3))
        													 .or(abilities(MultiblockAbility.INPUT_LASER).setMaxGlobalLimited(1));

        // layer the slices one behind the next
        return FactoryBlockPattern.start()
                .aisle(wall)
                .aisle(slice).setRepeatable(bDist - 1)
                .aisle(center)
                .aisle(slice).setRepeatable(fDist - 1)
                .aisle(wall)
                .where('S', selfPredicate())
                .where('B', states(getCasingState()).or(basePredicate))
                .where('X', wallPredicate.or(basePredicate))
                .where('K', wallPredicate) // the block beneath the controller must only be a casing for structure
                                           // dimension checks
                .where('F', mixingModules())
                .where(' ', frames(NTMaterials.HastelloyX))
                .build();
    }
	
	@NotNull
    protected IBlockState getCasingState() {
        return NTMetaBlocks.NT_CASINGS.getState(NTCasingType.MIXER_CASING);
    }

	@Override
	public ICubeRenderer getBaseTexture(IMultiblockPart sourcePart) 
	{
		return NTTextures.MIXER_CASING;
	}

	@Override
	public MetaTileEntity createMetaTileEntity(IGregTechTileEntity tileEntity) 
	{
		return new MetaTileEntityMixingVessel(metaTileEntityId);
	}
	
	@Override
    public void receiveCustomData(int dataId, PacketBuffer buf) {
        super.receiveCustomData(dataId, buf);
        if (dataId == GregtechDataCodes.UPDATE_STRUCTURE_SIZE) {
            this.lDist = buf.readInt();
            this.rDist = buf.readInt();
            this.bDist = buf.readInt();
            this.fDist = buf.readInt();
            this.hDist = buf.readInt();
        }
    }

    @Override
    public NBTTagCompound writeToNBT(@NotNull NBTTagCompound data) {
        super.writeToNBT(data);
        data.setInteger("lDist", this.lDist);
        data.setInteger("rDist", this.rDist);
        data.setInteger("bDist", this.fDist);
        data.setInteger("fDist", this.bDist);
        data.setInteger("hDist", this.hDist);
        return data;
    }

    @Override
    public void readFromNBT(NBTTagCompound data) {
        super.readFromNBT(data);
        this.lDist = data.hasKey("lDist") ? data.getInteger("lDist") : this.lDist;
        this.rDist = data.hasKey("rDist") ? data.getInteger("rDist") : this.rDist;
        this.hDist = data.hasKey("hDist") ? data.getInteger("hDist") : this.hDist;
        this.bDist = data.hasKey("bDist") ? data.getInteger("bDist") : this.bDist;
        this.fDist = data.hasKey("fDist") ? data.getInteger("fDist") : this.fDist;
        reinitializeStructurePattern();
    }

    @Override
    public void writeInitialSyncData(PacketBuffer buf) {
        super.writeInitialSyncData(buf);
        buf.writeInt(this.lDist);
        buf.writeInt(this.rDist);
        buf.writeInt(this.bDist);
        buf.writeInt(this.fDist);
        buf.writeInt(this.hDist);
        this.recipeMapWorkable.writeInitialSyncData(buf);
    }

    @Override
    public void receiveInitialSyncData(PacketBuffer buf) {
        super.receiveInitialSyncData(buf);
        this.lDist = buf.readInt();
        this.rDist = buf.readInt();
        this.bDist = buf.readInt();
        this.fDist = buf.readInt();
        this.hDist = buf.readInt();
        this.recipeMapWorkable.receiveInitialSyncData(buf);
    }
    
    @Override
    public List<MultiblockShapeInfo> getMatchingShapes() {
        ArrayList<MultiblockShapeInfo> shapeInfo = new ArrayList<>();
        MultiblockShapeInfo.Builder builder = MultiblockShapeInfo.builder()
                .aisle("XIEOX", "XXXXX", "XXXXX", "XXXXX", "XXXXX")
                .aisle("XXXXX", "X   X", "X   X", "X   X", "XFFFX")
                .aisle("XXXXX", "X   X", "X   X", "X   X", "XFSFX")
                .aisle("XXXXX", "X   X", "X   X", "X   X", "XFFFX")
                .aisle("XDMPX", "XXXXX", "XXXXX", "XXXXX", "XXXXX")
                .where('X', NTMetaBlocks.NT_CASINGS.getState(NTCasingType.MIXER_CASING))
                .where('S', NTMetaTileEntities.MIXING_VESSEL, EnumFacing.SOUTH)
                .where(' ', MetaBlocks.FRAMES.get(NTMaterials.HastelloyX).getBlock(NTMaterials.HastelloyX))
                .where('E', MetaTileEntities.ENERGY_INPUT_HATCH[GTValues.LV], EnumFacing.NORTH)
                .where('I', MetaTileEntities.ITEM_IMPORT_BUS[GTValues.LV], EnumFacing.NORTH)
                .where('O', MetaTileEntities.ITEM_EXPORT_BUS[GTValues.LV], EnumFacing.NORTH)
                .where('D', MetaTileEntities.FLUID_IMPORT_HATCH[GTValues.LV], EnumFacing.SOUTH)
                .where('P', MetaTileEntities.FLUID_EXPORT_HATCH[GTValues.LV], EnumFacing.SOUTH)
                .where('M',
                        () -> ConfigHolder.machines.enableMaintenance ? MetaTileEntities.MAINTENANCE_HATCH :
                                NTMetaBlocks.NT_CASINGS.getState(NTCasingType.MIXER_CASING),
                        EnumFacing.SOUTH)
                .where('F', NTMetaBlocks.MIXING_MODULES.getState(ModuleTier.ULV));
        
        shapeInfo.add(builder.build());
        
        return shapeInfo;
    }

    @Override
    public TraceabilityPredicate autoAbilities() {
        return autoAbilities(true, true, true, true, true, true, true);
    }
    
    @Override
    public TraceabilityPredicate autoAbilities(boolean checkEnergyIn,
                                               boolean checkMaintenance,
                                               boolean checkItemIn,
                                               boolean checkItemOut,
                                               boolean checkFluidIn,
                                               boolean checkFluidOut,
                                               boolean checkMuffler) {
        TraceabilityPredicate predicate = super.autoAbilities(checkMaintenance, checkMuffler);

        if (checkEnergyIn) {
            predicate = predicate.or(abilities(MultiblockAbility.INPUT_ENERGY).setMaxGlobalLimited(3).setPreviewCount(1))
            					 .or(abilities(MultiblockAbility.INPUT_LASER).setMaxGlobalLimited(1));
        }

        if (checkItemIn) {
            if (recipeMap.getMaxInputs() > 0) {
                predicate = predicate.or(abilities(MultiblockAbility.IMPORT_ITEMS).setPreviewCount(1));
            }
        }
        if (checkItemOut) {
            if (recipeMap.getMaxOutputs() > 0) {
                predicate = predicate.or(abilities(MultiblockAbility.EXPORT_ITEMS).setPreviewCount(1));
            }
        }
        if (checkFluidIn) {
            if (recipeMap.getMaxFluidInputs() > 0) {
                predicate = predicate.or(abilities(MultiblockAbility.IMPORT_FLUIDS).setPreviewCount(1));
            }
        }
        if (checkFluidOut) {
            if (recipeMap.getMaxFluidOutputs() > 0) {
                predicate = predicate.or(abilities(MultiblockAbility.EXPORT_FLUIDS).setPreviewCount(1));
            }
        }
        return predicate;
    }
    
    private float getProcessingSpeed()
    {
    	float f = (lDist - 2.0F) * -1;
    	f += processingSpeed;
    	return f;
    }
	
	private boolean areAllEqual(int check, int... others)
	{
		for(int value : others)
		{
			if (value != check)
			{
				return false;
			}
		}
		return true;
	}
	
	private class MixingVesselLogic extends MultiblockRecipeLogic
	{
		private MetaTileEntityMixingVessel mte;
		public MixingVesselLogic(MetaTileEntityMixingVessel tileEntity) 
		{
			super(tileEntity);
			this.mte = tileEntity;
		}
		
		@Override
		public int getParallelLimit()
		{
			return (int) Math.pow(4, mte.lDist - 1);
		}
		
		@Override
        protected void modifyOverclockPost(int[] resultOverclock, @NotNull IRecipePropertyStorage storage) {
            super.modifyOverclockPost(resultOverclock, storage);

            if(mte.getProcessingSpeed() > 0)
            {
            	resultOverclock[1] /= mte.getProcessingSpeed(); 
                resultOverclock[1] = Math.max(1, resultOverclock[1]);
            }
            if(mte.getProcessingSpeed() < 0)
            {
            	float f = Math.abs(mte.getProcessingSpeed()); // Convert back into positive value
            	resultOverclock[1] *= f; 
            }
        }
	}

}
