package nepjr.tech.metatileentities.multi.electric;

import java.util.Comparator;
import java.util.LinkedList;
import java.util.List;
import java.util.function.Supplier;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import gregtech.api.GTValues;
import gregtech.api.block.IHeatingCoilBlockStats;
import gregtech.api.capability.impl.MultiblockRecipeLogic;
import gregtech.api.metatileentity.MetaTileEntity;
import gregtech.api.metatileentity.interfaces.IGregTechTileEntity;
import gregtech.api.metatileentity.multiblock.IMultiblockPart;
import gregtech.api.metatileentity.multiblock.MultiblockAbility;
import gregtech.api.metatileentity.multiblock.MultiblockDisplayText;
import gregtech.api.metatileentity.multiblock.RecipeMapMultiblockController;
import gregtech.api.pattern.BlockPattern;
import gregtech.api.pattern.FactoryBlockPattern;
import gregtech.api.pattern.PatternMatchContext;
import gregtech.api.pattern.PatternStringError;
import gregtech.api.pattern.TraceabilityPredicate;
import gregtech.api.recipes.RecipeMap;
import gregtech.api.recipes.RecipeMaps;
import gregtech.api.recipes.recipeproperties.IRecipePropertyStorage;
import gregtech.api.util.BlockInfo;
import gregtech.api.util.GTUtility;
import gregtech.api.util.TextComponentUtil;
import gregtech.client.renderer.ICubeRenderer;
import gregtech.client.renderer.texture.Textures;
import gregtech.client.renderer.texture.cube.OrientedOverlayRenderer;
import nepjr.tech.api.NepTechAPI;
import nepjr.tech.api.block.ICentrifugingMotorStats;
import nepjr.tech.client.NTTextures;
import nepjr.tech.common.blocks.BlockNTCasings.NTCasingType;
import nepjr.tech.common.blocks.NTMetaBlocks;
import net.minecraft.block.state.IBlockState;
import net.minecraft.client.resources.I18n;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.text.ITextComponent;
import net.minecraft.util.text.TextFormatting;
import net.minecraft.world.World;

public class MetaTileEntityIndustrialCentrifuge extends RecipeMapMultiblockController
{
	private int moduleTier;
	private float processingSpeed;
	
	public MetaTileEntityIndustrialCentrifuge(ResourceLocation metaTileEntityId, RecipeMap<?> recipeMap)
	{
		super(metaTileEntityId, recipeMap);
		this.recipeMapWorkable = new CentrifugingRecipeLogic(this);
	}

	@Override
	protected @NotNull BlockPattern createStructurePattern()
	{
		return FactoryBlockPattern.start()
				.aisle(" CCC ", "CCCCC", "CCCCC", "CCCCC", " CCC ")
				.aisle("CCCCC", "CMAMC", "CAMAC", "CMAMC", "CCCCC")
				.aisle("CCCCC", "CAMAC", "CMAMC", "CAMAC", "CCOCC")
				.aisle("CCCCC", "CMAMC", "CAMAC", "CMAMC", "CCCCC")
				.aisle(" CCC ", "CCCCC", "CCSCC", "CCCCC", " CCC ")
				.where('C', states(getCasingState()).or(autoAbilities(true, true, true, true, true, true, false)))
				.where('O', possibleMuffler())
				.where('M', centrifugingMotors())
				.where('A', getIntMisc())
				.where(' ', any())
				.where('S', selfPredicate())
				.build();
	}
	
	// Allow all fertilizers, and require them to have the same type.
    public static Supplier<TraceabilityPredicate> CENTRIFUGING_MOTORS = () -> new TraceabilityPredicate(blockWorldState -> {
        IBlockState blockState = blockWorldState.getBlockState();
        if (NepTechAPI.CENTRIFUGING_MOTORS.containsKey(blockState)) {
        	ICentrifugingMotorStats stats = NepTechAPI.CENTRIFUGING_MOTORS.get(blockState);
            Object currentMotor = blockWorldState.getMatchContext().getOrPut("CentrifugingMotor", stats);
            if (!currentMotor.equals(stats)) {
                blockWorldState.setError(new PatternStringError("neptech.multiblock.pattern.error.centrifuging_motor"));
                return false;
            }
            blockWorldState.getMatchContext().getOrPut("VABlock1", new LinkedList<>()).add(blockWorldState.getPos());
            return true;
        }
        return false;
    }, () -> NepTechAPI.CENTRIFUGING_MOTORS.entrySet().stream()
            // sort to make autogenerated jei previews not pick random coils each game load
            .sorted(Comparator.comparingInt(entry -> entry.getValue().getTier()))
            .map(entry -> new BlockInfo(entry.getKey(), null))
            .toArray(BlockInfo[]::new))
                    .addTooltips("neptech.multiblock.pattern.error.centrifuging_motor");
    
    public static TraceabilityPredicate centrifugingMotors() {
        return CENTRIFUGING_MOTORS.get();
    }
    
    @Override
    protected void formStructure(PatternMatchContext context) {
        super.formStructure(context);
        
        Object centrifugingMotor = context.get("CentrifugingMotor");
        Object coils = context.get("CoilType");
        if (centrifugingMotor instanceof ICentrifugingMotorStats) {
            
        	if(getRecipeMap() == RecipeMaps.THERMAL_CENTRIFUGE_RECIPES && coils instanceof IHeatingCoilBlockStats)
        	{
        		int tier = ((IHeatingCoilBlockStats) coils).getTier();
        		this.processingSpeed = (float) (2 * (((50 * (tier + 1)))) / 100);
        	}
        	else
        	{
        		this.processingSpeed = ((ICentrifugingMotorStats) centrifugingMotor).getProcessingSpeed();
        	}
            this.moduleTier = ((ICentrifugingMotorStats) centrifugingMotor).getTier();
        } else {
            this.processingSpeed = 0;
            this.moduleTier = GTValues.ULV;
        }
	}
    
    @Override
    protected void addDisplayText(List<ITextComponent> textList)
    {
        MultiblockDisplayText.builder(textList, isStructureFormed())
                .setWorkingStatus(recipeMapWorkable.isWorkingEnabled(), recipeMapWorkable.isActive())
                .addEnergyUsageLine(recipeMapWorkable.getEnergyContainer())
                .addEnergyTierLine(GTUtility.getTierByVoltage(recipeMapWorkable.getMaxVoltage()))
                .addParallelsLine(recipeMapWorkable.getParallelLimit())
                .addCustom(tl -> {
                	if(isStructureFormed())
                	{
                		ITextComponent processingSpeed = TextComponentUtil.stringWithColor(TextFormatting.YELLOW, String.valueOf((int) (100 * getProcessingSpeed())));
                        ITextComponent energyDiscount = TextComponentUtil.stringWithColor(TextFormatting.YELLOW, String.valueOf(getEuUsage()));

                        tl.add(TextComponentUtil.translationWithColor(TextFormatting.GRAY, "neptech.processing_speed_bonus", processingSpeed));
                        tl.add(TextComponentUtil.translationWithColor(TextFormatting.GRAY, "neptech.energy_discount", energyDiscount));
                	}
                })
                .addWorkingStatusLine()
                .addProgressLine(recipeMapWorkable.getProgressPercent());
    }
    
    @Override
    public void addInformation(ItemStack stack, @Nullable World player, @NotNull List<String> tooltip,
                               boolean advanced) {
        super.addInformation(stack, player, tooltip, advanced);
        if(getRecipeMap() == RecipeMaps.THERMAL_CENTRIFUGE_RECIPES)
        {
        	tooltip.add(TextFormatting.GRAY + I18n.format("neptech.industrial_thermal_centrifuge.tooltip"));
        }
        else
        {
        	tooltip.add(TextFormatting.GRAY + I18n.format("neptech.industrial_centrifuge.tooltip"));
        }
    }

	@Override
	public ICubeRenderer getBaseTexture(IMultiblockPart sourcePart)
	{
		// TODO Auto-generated method stub
		return NTTextures.VIBRATION_SAFE_CASING;
	}
	
	private IBlockState getCasingState()
	{
		return NTMetaBlocks.NT_CASINGS.getState(NTCasingType.VIBRATION_SAFE_CASING);
	}
	
	private TraceabilityPredicate getIntMisc()
	{
		return getRecipeMap() == RecipeMaps.THERMAL_CENTRIFUGE_RECIPES ? heatingCoils() :
																		 air();
	}
	
	private TraceabilityPredicate possibleMuffler()
	{
		return getRecipeMap() == RecipeMaps.THERMAL_CENTRIFUGE_RECIPES ? abilities(MultiblockAbility.MUFFLER_HATCH) :
			 															 states(getCasingState());
	}
	
	@Override
	public OrientedOverlayRenderer getFrontOverlay()
	{
		return getRecipeMap() == RecipeMaps.THERMAL_CENTRIFUGE_RECIPES ? Textures.THERMAL_CENTRIFUGE_OVERLAY :
			 															 Textures.CENTRIFUGE_OVERLAY;
	}

	@Override
	public MetaTileEntity createMetaTileEntity(IGregTechTileEntity tileEntity)
	{
		// TODO Auto-generated method stub
		return new MetaTileEntityIndustrialCentrifuge(metaTileEntityId, recipeMap);
	}
	
	@Override 
	public boolean hasMufflerMechanics()
	{
		return getRecipeMap() == RecipeMaps.THERMAL_CENTRIFUGE_RECIPES;
	}
	
	public int getEuUsage()
	{
		return 100 - (moduleTier*5);
	}
	
	public int getParallels()
	{
		return (int) Math.pow(4, moduleTier);
	}
	
	public float getProcessingSpeed()
	{
		return processingSpeed;
	}
	
	private class CentrifugingRecipeLogic extends MultiblockRecipeLogic
	{
		private MetaTileEntityIndustrialCentrifuge mte;
		public CentrifugingRecipeLogic(MetaTileEntityIndustrialCentrifuge tileEntity)
		{
			super(tileEntity);
			this.mte = tileEntity;
		}
		
		@Override
        protected void modifyOverclockPost(int[] resultOverclock, @NotNull IRecipePropertyStorage storage) {
            super.modifyOverclockPost(resultOverclock, storage);
            
            resultOverclock[0] *= mte.getEuUsage(); 
            resultOverclock[0] = Math.max(1, resultOverclock[0]);
            
            resultOverclock[1] /= mte.getProcessingSpeed(); 
            resultOverclock[1] = Math.max(1, resultOverclock[0]);
        }
		
		@Override
		public int getParallelLimit()
		{
			return mte.getParallels();
		}
		
	}

}
