package nepjr.tech.metatileentities.multi.electric;

import java.util.Comparator;
import java.util.LinkedList;
import java.util.List;
import java.util.function.Supplier;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import gregtech.api.capability.impl.MultiblockRecipeLogic;
import gregtech.api.metatileentity.MetaTileEntity;
import gregtech.api.metatileentity.interfaces.IGregTechTileEntity;
import gregtech.api.metatileentity.multiblock.IMultiblockPart;
import gregtech.api.metatileentity.multiblock.RecipeMapMultiblockController;
import gregtech.api.pattern.BlockPattern;
import gregtech.api.pattern.FactoryBlockPattern;
import gregtech.api.pattern.PatternMatchContext;
import gregtech.api.pattern.PatternStringError;
import gregtech.api.pattern.TraceabilityPredicate;
import gregtech.api.recipes.RecipeMaps;
import gregtech.api.recipes.recipeproperties.IRecipePropertyStorage;
import gregtech.api.util.BlockInfo;
import gregtech.client.renderer.ICubeRenderer;
import gregtech.client.renderer.texture.Textures;
import gregtech.client.renderer.texture.cube.OrientedOverlayRenderer;
import gregtech.client.utils.TooltipHelper;
import nepjr.tech.api.NepTechAPI;
import nepjr.tech.api.block.ICrushingWheelStats;
import nepjr.tech.client.NTTextures;
import nepjr.tech.common.blocks.NTMetaBlocks;
import nepjr.tech.common.blocks.BlockNTCasings.NTCasingType;
import net.minecraft.block.state.IBlockState;
import net.minecraft.client.resources.I18n;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.text.TextFormatting;
import net.minecraft.world.World;

public class MetaTileEntityPulverizer extends RecipeMapMultiblockController
{
	private int processingSpeed;
	private int maxParallels;
	public MetaTileEntityPulverizer(ResourceLocation metaTileEntityId)
	{
		super(metaTileEntityId, RecipeMaps.MACERATOR_RECIPES);
		this.recipeMapWorkable = new PulverizerRecipeLogic(this);
	}

	@Override
	protected @NotNull BlockPattern createStructurePattern()
	{
		return FactoryBlockPattern.start()
				.aisle("CCCCC", "CCCCC", "CCCCC", "CCCCC", "CCCCC")
				.aisle("CCCCC", "CWWWC", "CWWWC", "CWWWC", "CWWWC")
				.aisle("CCCCC", "CWWWC", "CWWWC", "CWWWC", "CWWWC")
				.aisle("CCCCC", "CWWWC", "CWWWC", "CWWWC", "CWWWC")
				.aisle("CCCCC", "CCCCC", "CCSCC", "CCCCC", "CCCCC")
				.where('C', states(getCasingState()).or(autoAbilities()))
				.where('W', crushingWheels())
				.where('S', selfPredicate())
				.build();
	}
	
	@Override
    public void addInformation(ItemStack stack, @Nullable World player, List<String> tooltip, boolean advanced)
	{
        super.addInformation(stack, player, tooltip, advanced);
        tooltip.add(TextFormatting.GREEN + I18n.format("neptech.crushing_wheels.pulverizer"));
    }
	
	@Override
    protected void formStructure(PatternMatchContext context) {
        super.formStructure(context);
        Object crushingWheels = context.get("CrushingWheels");
        if (crushingWheels instanceof ICrushingWheelStats) {
            this.maxParallels = (int) Math.pow(8, ((ICrushingWheelStats) crushingWheels).getTier());
            this.processingSpeed = (int) ((ICrushingWheelStats) crushingWheels).getProcessingSpeed();
        } else {
            this.maxParallels = 0;
            this.processingSpeed = 0;
        }
    }
	
	// Allow all fertilizers, and require them to have the same type.
    public static Supplier<TraceabilityPredicate> CRUSHING_WHEELS = () -> new TraceabilityPredicate(blockWorldState -> {
        IBlockState blockState = blockWorldState.getBlockState();
        if (NepTechAPI.CRUSHING_WHEELS.containsKey(blockState)) {
        	ICrushingWheelStats stats = NepTechAPI.CRUSHING_WHEELS.get(blockState);
            Object currentCoil = blockWorldState.getMatchContext().getOrPut("CrushingWheels", stats);
            if (!currentCoil.equals(stats)) {
                blockWorldState.setError(new PatternStringError("neptech.multiblock.pattern.error.crushing_wheels"));
                return false;
            }
            blockWorldState.getMatchContext().getOrPut("VABlock", new LinkedList<>()).add(blockWorldState.getPos());
            return true;
        }
        return false;
    }, () -> NepTechAPI.CRUSHING_WHEELS.entrySet().stream()
            // sort to make autogenerated jei previews not pick random coils each game load
            .sorted(Comparator.comparingInt(entry -> entry.getValue().getTier()))
            .map(entry -> new BlockInfo(entry.getKey(), null))
            .toArray(BlockInfo[]::new))
                    .addTooltips("neptech.multiblock.pattern.error.crushing_wheels");
    
    public static TraceabilityPredicate crushingWheels() 
    {
        return CRUSHING_WHEELS.get();
    }
    
    private IBlockState getCasingState()
    {
    	return NTMetaBlocks.NT_CASINGS.getState(NTCasingType.MACERATOR_CASING);
    }

	@Override
	public ICubeRenderer getBaseTexture(IMultiblockPart sourcePart)
	{
		return NTTextures.MACERATOR_CASING;
	}
	
	@Override
    protected @NotNull OrientedOverlayRenderer getFrontOverlay() {
        return Textures.ROCK_BREAKER_OVERLAY;
    }

	@Override
	public MetaTileEntity createMetaTileEntity(IGregTechTileEntity tileEntity)
	{
		return new MetaTileEntityPulverizer(metaTileEntityId);
	}
	
	private int getMaxParallels()
	{
		return maxParallels;
	}
	
	private int getProcessingSpeed()
	{
		return processingSpeed;
	}

	private class PulverizerRecipeLogic extends MultiblockRecipeLogic
	{
		private MetaTileEntityPulverizer mte;
		public PulverizerRecipeLogic(MetaTileEntityPulverizer tileEntity)
		{
			super(tileEntity);
			this.mte = tileEntity;
		}
		
		@Override
		public int getParallelLimit()
		{
			return mte.getMaxParallels();
		}
		
		@Override
        protected void modifyOverclockPost(int[] resultOverclock, @NotNull IRecipePropertyStorage storage)
		{
            super.modifyOverclockPost(resultOverclock, storage);
            resultOverclock[1] /= mte.getProcessingSpeed(); 
            resultOverclock[1] = Math.max(1, resultOverclock[1]);
        }	
		
	}
}
