package nepjr.tech.api.metatileentity;

import java.util.Comparator;
import java.util.LinkedList;
import java.util.List;
import java.util.function.Supplier;

import org.jetbrains.annotations.Nullable;

import gregtech.api.capability.impl.MultiblockRecipeLogic;
import gregtech.api.metatileentity.multiblock.RecipeMapMultiblockController;
import gregtech.api.pattern.PatternStringError;
import gregtech.api.pattern.TraceabilityPredicate;
import gregtech.api.recipes.RecipeMap;
import gregtech.api.util.BlockInfo;
import gregtech.client.utils.TooltipHelper;
import nepjr.tech.api.NepTechAPI;
import nepjr.tech.api.block.IFertilizedDirtBlockStats;
import net.minecraft.block.state.IBlockState;
import net.minecraft.client.resources.I18n;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.text.TextFormatting;
import net.minecraft.world.World;

public abstract class NTMetaTileEntity extends RecipeMapMultiblockController 
{
	// We store the parallels as Long to prevent potential buffer overflows
	private long parallels;
	private float energyDiscount = 1;
	private float processingSpeed = 1;
	private boolean hasPerfectOC;
	
	public NTMetaTileEntity(ResourceLocation metaTileEntityId, RecipeMap<?> recipeMap, boolean perfectOC, float energyDiscount, float processingSpeed) 
	{
		super(metaTileEntityId, recipeMap);
		this.recipeMapWorkable = new NTMultiblockLogic(this, perfectOC);
		this.hasPerfectOC = perfectOC;
		this.energyDiscount = energyDiscount;
		this.processingSpeed = processingSpeed;
	}
	
	@Override
    public void addInformation(ItemStack stack, @Nullable World player, List<String> tooltip, boolean advanced) {
        super.addInformation(stack, player, tooltip, advanced);
        if(hasPerfectOC)
        {
        	tooltip.add(TooltipHelper.RAINBOW_SLOW + I18n.format("gregtech.machine.perfect_oc"));
        }
        if(getParallels() > 0)
        {
        	tooltip.add(TextFormatting.GREEN + I18n.format("neptech.parallels", getParallels()));
        }
        if(getProcessingSpeed() < 1)
        {
        	tooltip.add(TextFormatting.RED + I18n.format("neptech.processing_speed", getProcessingSpeed() * 100));
        }
        if(getProcessingSpeed() > 1)
        {
        	tooltip.add(TextFormatting.GREEN + I18n.format("neptech.processing_speed", getProcessingSpeed() * 100));
        }
        if(getEnergyDiscount() < 1)
        {
        	tooltip.add(TextFormatting.GREEN + I18n.format("neptech.energy_discount", getEnergyDiscount() * 100));
        }
        if(getEnergyDiscount() > 1)
        {
        	tooltip.add(TextFormatting.RED + I18n.format("neptech.energy_discount", getEnergyDiscount() * 100));
        }
    }
	
	public float getEnergyDiscount()
	{
		return energyDiscount;
	}
	
	public float getProcessingSpeed()
	{
		return processingSpeed;
	}
	
	public long getParallels()
	{
		if(parallels > 0)
		{
			return parallels;
		}
		else
		{
			return 1;
		}
	}
	
	public void setParallels(int value)
	{
		parallels = value;
	}
	
	// Allow all fertilizers, and require them to have the same type.
    public static Supplier<TraceabilityPredicate> FERTILIZED_DIRT = () -> new TraceabilityPredicate(blockWorldState -> {
        IBlockState blockState = blockWorldState.getBlockState();
        if (NepTechAPI.FERTILIZED_DIRTS.containsKey(blockState)) {
        	IFertilizedDirtBlockStats stats = NepTechAPI.FERTILIZED_DIRTS.get(blockState);
            Object currentCoil = blockWorldState.getMatchContext().getOrPut("FertilizerType", stats);
            if (!currentCoil.equals(stats)) {
                blockWorldState.setError(new PatternStringError("neptech.multiblock.pattern.error.fertilizer"));
                return false;
            }
            blockWorldState.getMatchContext().getOrPut("VABlock", new LinkedList<>()).add(blockWorldState.getPos());
            return true;
        }
        return false;
    }, () -> NepTechAPI.FERTILIZED_DIRTS.entrySet().stream()
            // sort to make autogenerated jei previews not pick random fertilizers each game load
            .sorted(Comparator.comparingInt(entry -> entry.getValue().getTier()))
            .map(entry -> new BlockInfo(entry.getKey(), null))
            .toArray(BlockInfo[]::new))
                    .addTooltips("neptech.multiblock.pattern.error.fertilizer");
    
    public static TraceabilityPredicate fertilizedDirt() 
    {
        return FERTILIZED_DIRT.get();
    }
    
    protected class NTMultiblockLogic extends MultiblockRecipeLogic
    {
    	protected final NTMetaTileEntity mte;
		public NTMultiblockLogic(NTMetaTileEntity tileEntity, boolean hasPerfectOC) 
		{
			super(tileEntity, hasPerfectOC);
			mte = (NTMetaTileEntity) this.getMetaTileEntity();
		}
		
		@Override
		public int getParallelLimit()
		{
			if(mte.getParallels() <= Integer.MAX_VALUE)
			{
				return (int) mte.getParallels();
			}
			if(mte.getParallels() > Integer.MAX_VALUE)
			{
				return Integer.MAX_VALUE;
			}
			else
			{
				return 1;
			}
		}
    }
}
