package nepjr.tech.api.metatileentity;

import java.util.Comparator;
import java.util.LinkedList;
import java.util.function.Supplier;

import gregicality.multiblocks.api.metatileentity.GCYMRecipeMapMultiblockController;
import gregtech.api.metatileentity.multiblock.MultiMapMultiblockController;
import gregtech.api.metatileentity.multiblock.RecipeMapMultiblockController;
import gregtech.api.pattern.PatternStringError;
import gregtech.api.pattern.TraceabilityPredicate;
import gregtech.api.recipes.RecipeMap;
import gregtech.api.util.BlockInfo;
import nepjr.tech.api.NepTechAPI;
import nepjr.tech.api.block.IFertilizedDirtBlockStats;
import net.minecraft.block.state.IBlockState;
import net.minecraft.util.ResourceLocation;

public abstract class NTMetaTileEntity extends GCYMRecipeMapMultiblockController {

	public NTMetaTileEntity(ResourceLocation metaTileEntityId, RecipeMap<?> recipeMap) 
	{
		super(metaTileEntityId, new RecipeMap<?>[] { recipeMap });
	}
	
	// Allow all fertilizers, and require them to have the same type.
    public static Supplier<TraceabilityPredicate> FERTILIZED_DIRT = () -> new TraceabilityPredicate(blockWorldState -> {
        IBlockState blockState = blockWorldState.getBlockState();
        if (NepTechAPI.FERTILIZED_DIRTS.containsKey(blockState)) {
        	IFertilizedDirtBlockStats stats = NepTechAPI.FERTILIZED_DIRTS.get(blockState);
            Object currentCoil = blockWorldState.getMatchContext().getOrPut("FertilizerType", stats);
            if (!currentCoil.equals(stats)) {
                blockWorldState.setError(new PatternStringError("neptech.multiblock.pattern.error.fertilizer"));
                return false;
            }
            blockWorldState.getMatchContext().getOrPut("VABlock", new LinkedList<>()).add(blockWorldState.getPos());
            return true;
        }
        return false;
    }, () -> NepTechAPI.FERTILIZED_DIRTS.entrySet().stream()
            // sort to make autogenerated jei previews not pick random coils each game load
            .sorted(Comparator.comparingInt(entry -> entry.getValue().getTier()))
            .map(entry -> new BlockInfo(entry.getKey(), null))
            .toArray(BlockInfo[]::new))
                    .addTooltips("neptech.multiblock.pattern.error.fertilizer");
    
    public static TraceabilityPredicate fertilizedDirt() {
        return FERTILIZED_DIRT.get();
    }

}
