package nepjr.tech.common.metatileentities.multi.electric;

import gregtech.api.GTValues;
import gregtech.api.capability.impl.MultiblockRecipeLogic;
import gregtech.api.metatileentity.MetaTileEntity;
import gregtech.api.metatileentity.interfaces.IGregTechTileEntity;
import gregtech.api.metatileentity.multiblock.IMultiblockPart;
import gregtech.api.metatileentity.multiblock.MultiMapMultiblockController;
import gregtech.api.metatileentity.multiblock.RecipeMapMultiblockController;
import gregtech.api.pattern.*;
import gregtech.api.recipes.RecipeMap;
import gregtech.api.recipes.RecipeMaps;
import gregtech.api.recipes.recipeproperties.IRecipePropertyStorage;
import gregtech.api.util.BlockInfo;
import gregtech.client.renderer.ICubeRenderer;
import gregtech.client.renderer.texture.Textures;
import gregtech.client.renderer.texture.cube.OrientedOverlayRenderer;
import nepjr.tech.api.NepTechAPI;
import nepjr.tech.api.block.IMagnetStats;
import nepjr.tech.api.block.IMetalworkingModuleStats;
import nepjr.tech.client.NTTextures;
import nepjr.tech.common.blocks.BlockNTCasings;
import nepjr.tech.common.blocks.NTMetaBlocks;
import net.minecraft.block.state.IBlockState;
import net.minecraft.init.Blocks;
import net.minecraft.util.ResourceLocation;
import org.jetbrains.annotations.NotNull;

import java.util.Comparator;
import java.util.LinkedList;
import java.util.function.Supplier;

public class MetaTileEntityLargeElectromagnet extends MultiMapMultiblockController
{
    protected float processingSpeed;
    protected int moduleTier;
    public MetaTileEntityLargeElectromagnet(ResourceLocation metaTileEntityId) {
        super(metaTileEntityId, new RecipeMap[]{
                RecipeMaps.POLARIZER_RECIPES,
                RecipeMaps.ELECTROMAGNETIC_SEPARATOR_RECIPES
        });
        this.recipeMapWorkable = new ElectromagnetRecipeLogic(this);
    }

    @Override
    protected void formStructure(PatternMatchContext context) {
        super.formStructure(context);

        Object magnetModules = context.get("MagnetModules");
        if (magnetModules instanceof IMagnetStats)
        {
            this.processingSpeed = ((IMagnetStats) magnetModules).getProcessingSpeed();
            this.moduleTier = ((IMagnetStats) magnetModules).getTier();
        }
        else
        {
            this.processingSpeed = 0;
            this.moduleTier = GTValues.LV;
        }
    }

    @Override
    protected @NotNull BlockPattern createStructurePattern() {
        return FactoryBlockPattern.start()
                .aisle("CCCCC", "CCCCC", "CCCCC")
                .aisle("CCCCC", "CM MC", "CCCCC")
                .aisle("CCCCC", "CCSCC", "CCCCC")
                .where('C', states(getCasingState()).or(autoAbilities()))
                .where('M', magnets())
                .where(' ', air())
                .where('S', selfPredicate())
                .build();
    }

    private IBlockState getCasingState()
    {
        return NTMetaBlocks.NT_CASINGS.getState(BlockNTCasings.NTCasingType.NONCONDUCTING_CASING);
    }

    public static Supplier<TraceabilityPredicate> MAGNET_MODULES = () -> new TraceabilityPredicate(blockWorldState -> {
        IBlockState blockState = blockWorldState.getBlockState();
        if (NepTechAPI.MAGNETS.containsKey(blockState)) {
            IMagnetStats stats = NepTechAPI.MAGNETS.get(blockState);
            Object currentCoil = blockWorldState.getMatchContext().getOrPut("MagnetModules", stats);
            if (!currentCoil.equals(stats)) {
                blockWorldState.setError(new PatternStringError("neptech.multiblock.pattern.error.magnet_modules"));
                return false;
            }
            blockWorldState.getMatchContext().getOrPut("VABlock", new LinkedList<>()).add(blockWorldState.getPos());
            return true;
        }
        return false;
    }, () -> NepTechAPI.MAGNETS.entrySet().stream()
            // sort to make autogenerated jei previews not pick random coils each game load
            .sorted(Comparator.comparingInt(entry -> entry.getValue().getTier()))
            .map(entry -> new BlockInfo(entry.getKey(), null))
            .toArray(BlockInfo[]::new))
            .addTooltips("neptech.multiblock.pattern.error.magnet_modules");

    public static TraceabilityPredicate magnets() {
        return MAGNET_MODULES.get();
    }

    @Override
    public ICubeRenderer getBaseTexture(IMultiblockPart sourcePart) {
        return NTTextures.NONCONDUCTING_CASING;
    }

    @Override
    protected @NotNull OrientedOverlayRenderer getFrontOverlay() {
        return Textures.ELECTROMAGNETIC_SEPARATOR_OVERLAY;
    }

    @Override
    public MetaTileEntity createMetaTileEntity(IGregTechTileEntity tileEntity) {
        return new MetaTileEntityLargeElectromagnet(metaTileEntityId);
    }

    public float getProcessingSpeed()
    {
        return processingSpeed;
    }

    public int getModuleTier()
    {
        return moduleTier;
    }

    private class ElectromagnetRecipeLogic extends MultiblockRecipeLogic
    {
        private MetaTileEntityLargeElectromagnet mte;
        public ElectromagnetRecipeLogic(MetaTileEntityLargeElectromagnet tileEntity)
        {
            super(tileEntity);
            mte = tileEntity;
        }

        @Override
        protected void modifyOverclockPost(int[] resultOverclock, @NotNull IRecipePropertyStorage storage)
        {
            super.modifyOverclockPost(resultOverclock, storage);

            if(mte.getProcessingSpeed() > 0.0f)
            {
                resultOverclock[1] /= (int) mte.getProcessingSpeed();
                resultOverclock[1] = Math.max(1, resultOverclock[1]);
            }
            if(mte.getProcessingSpeed() < 0.0f)
            {
                float f = Math.abs(mte.getProcessingSpeed()); // Convert back into positive value
                f += 1.0f; // Add one
                resultOverclock[1] *= (int) f;
            }
        }

        @Override
        public int getParallelLimit()
        {
            return (int) Math.pow(8, getModuleTier());
        }
    }
}
